# Copyright (c) 2025-present, Royal Bank of Canada.
# All rights reserved.
#
# This source code is licensed under the license found in the
# LICENSE file in the root directory of this source tree.

#!/bin/bash
#SBATCH --gres=gpu:1
#SBATCH --mem=30G

echo $CUDA_VISIBLE_DEVICES

GATING_INIT=$4
LOSS_ALPHA=$3
LOW_RANK=$2
TTA=PETSA_RANK_${LOW_RANK}_LOSSALPHA_${LOSS_ALPHA}_GATINGINIT_${GATING_INIT}

export CUDA_VISIBLE_DEVICES=$1
echo $CUDA_VISIBLE_DEVICES

DATASET="exchange_rate"
PRED_LEN=720
MODEL="iTransformer"
CHECKPOINT_DIR="./checkpoints/${MODEL}/${DATASET}_${PRED_LEN}/"
RESULT_DIR="./results/${TTA}/"
OUTPUT="${TTA}_${MODEL}_${DATASET}_${PRED_LEN}.txt"
BASE_LR=0.005
WEIGHT_DECAY=0.0

python main.py DATA.NAME ${DATASET} DATA.PRED_LEN ${PRED_LEN} MODEL.NAME ${MODEL} MODEL.pred_len ${PRED_LEN} TRAIN.ENABLE False TRAIN.CHECKPOINT_DIR ${CHECKPOINT_DIR} TTA.ENABLE True TTA.SOLVER.BASE_LR ${BASE_LR} TTA.SOLVER.WEIGHT_DECAY ${WEIGHT_DECAY} TTA.PETSA.GATING_INIT ${GATING_INIT} TTA.PETSA.RANK ${LOW_RANK} TTA.PETSA.LOSS_ALPHA ${LOSS_ALPHA} RESULT_DIR ${RESULT_DIR} > ${OUTPUT}
